@url = http://localhost:3111

### Register a new user ###

POST {{url}}/register
Content-Type: application/json

{
  "name": "Mohammad",
  "email": "Mohammad@example.com",
  "password": "123"
}


### Sign in as a user ###

POST {{url}}/signin
Content-Type: application/json

{
  "email": "Mohammad@example.com",
  "password": "123"
}


### Get current user's information ###

GET {{url}}/me
Cookie: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTW9oYW1tYWQiLCJpYXQiOjE2ODU0OTg4MTEsImV4cCI6MTY4NTU4NTIxMX0.SO4G4K7W2qfaCtKoB_lF7IOziydwsegKhz20SvKH-qE



### Log out the user ###

GET {{url}}/logout
